### ISSUE TITLE
develop an easier way to create issues in github from a prisma request

### ISSUE THREAD

**Issue by lucacioria** [buildo/prisma#11]
## requirements
- requests in prisma are migrated to github issues manually, because a github issues is better defined and must be written by devs, not customers
  - however, it can be useful to prepopulate a github issue with:
    - issue description, requirements section = description of the trello card
    - issue title = title of the trello card

## specs
- a card is added to "requests" list
  - call nemobot for templates (https://github.com/buildo/nemobot/issues/64)
  - add a url attachment for each template

NB: if a template is updated after the attachment is added the card will keep "using" the old one.

**Comment by lucacioria** [comment]
@FrancescoCioria @gabro do you have ideas on how this could be technically achieved? It's not a priority, but I wanted to have an idea of feasibility and your opinion on the issue in general.

**Comment by gabro** [comment]
Link with pre-filled content should be easy

**Comment by gabro** [comment]
E.g.

https://github.com/buildo/prisma/issues/new?title=HeyHey&body=bodybodybody&labels[]=WIP

**Comment by lucacioria** [comment]
super cool! I was not aware of that functionality.

**Comment by gabro** [comment]
we use it for workflow-pal ;)

**Comment by FrancescoCioria** [comment]
`prisma` could simply add an attachment to the cards addd to "requests" with the url described be gabro and keep it updated if it changes (to be verified).

PS: the description can be in `markdown` which means we can format it (like add a hidden link to trello issue or something)

**Comment by FrancescoCioria** [comment]
waiting for https://github.com/buildo/nemobot/issues/64.

PS: I updated the specs
