### ISSUE TITLE
use original card instead of creating new ones

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/prisma#17]
## requirements
prisma new-issue links should populate default issue body with card content, link to trello card and  hidden pointer to card id (will be used by prisma).
when customer issue is created:
- if it contains a pointer to original card update the card:
  - move to backlog
  - remove new-issue links
  - add link to github
  - update title
- if it doesn't not contain a pointer:
  - create new card in backlog (this is already implemented)

## specs
- update new-issue links to contain link to trello, card.desc and pointer. for pointer do something  like this to add an invisible comment with the card id inside:
```js
// add new new-issue links
const toAdd = await Promise.all(issueTypes.map(it => {
  return nemobot.getTemplates({ t: it })
    .then(res => {
      const { body, ..._query } = querystring.parse(res[it].computedQuery);
      const query = {
        ..._query,
        body: `${body}\n\n[@prismabot comment: don't remove]: # (Card: #${cardId})`
      };

      return {
        name: it,
        url: [url, org, repo, 'issues', 'new', `?${querystring.stringify(query)}`].join('/')
      };
    });
}));
```

**Comment by lucacioria** [comment]
this is becoming high priority as people are not doing it manually but simply ignoring this step :p
