### ISSUE TITLE
treat any column starting with `(r)` as a requests column

### ISSUE THREAD

**Issue by lucacioria** [buildo/prisma#20]
## requirements
- we only considered one column named `requests` acting as requests to be refined into issues
- in complex projects, we typically need more than one column, such as in `PRISMA - AlinIQ`:
https://www.dropbox.com/s/1gn8bk0xuf0ixm0/Screenshot%202016-04-26%2010.52.54.png?dl=0
- also, the `icebox` column is actually a `requests` column with an added meaning of low priority, so it should also be treated as request

**treating a column as a requests column means, for now, that a link to quickly open an issue in github is added by PRISMA**

## specs
- update `RequestCardUpdated` and `RequestCardCreated` validators:
  - any list starting with `(r)`

**Comment by lucacioria** [comment]
@FrancescoCioria does this sound correct to you?

**Comment by FrancescoCioria** [comment]
@lucacioria edited specs ^

**Comment by lucacioria** [comment]
@FrancescoCioria yes I was suggesting to add `(r)` to icebox, too, and treat it as the others

**Comment by lucacioria** [comment]
![image](https://cloud.githubusercontent.com/assets/554092/14812648/556e8d9a-0b9e-11e6-9f9e-c2826a3b82e9.png)
