### ISSUE TITLE
reliably keep Prisma card and GitHub issue in sync where relevant

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/prisma#31]
[Trello card](https://trello.com/c/57c01020598fbb89e7ebdc4d/)

## stories

- as a PM, I want to see changes in GitHub issue descriptions reflected in Prisma so as to see how things evolve while developing

- as a PM, I want to monitor the ongoing process of sub-issues in macro issues without having to open GitHub so as to know the details of progress without requiring devs to update in PRISMA

## requirements

- implement 2 way sync of card description  <=> issue body for issues with `customers` label
  - do not apply or merge github templates, if created in prisma, there is no other templating happening in github
  - eventually we'll sync templates with trello so that they're consistent

## specs

- optionally, implementation details if needed

[@prismabot comment: don't remove]: # (Card: #57c01020598fbb89e7ebdc4d)

**Comment by lucacioria** [comment]
@FrancescoCioria I've udpated requirements, did I miss something?
